# Generated by Django 4.2.4 on 2023-11-21 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChooseProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_co_no', models.TextField()),
                ('kor_co_nm', models.TextField()),
                ('fin_prdt_cd', models.TextField()),
                ('fin_prdt_nm', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DepositProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_co_no', models.TextField()),
                ('kor_co_nm', models.TextField()),
                ('fin_prdt_cd', models.TextField(unique=True)),
                ('fin_prdt_nm', models.TextField()),
                ('join_way', models.TextField(null=True)),
                ('join_member', models.TextField(null=True)),
                ('join_deny', models.IntegerField(null=True)),
                ('max_limit', models.TextField(null=True)),
                ('spcl_cnd', models.TextField(null=True)),
                ('mtrt_int', models.TextField(null=True)),
                ('etc_note', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_co_no', models.TextField(unique=True)),
                ('kor_co_nm', models.TextField()),
                ('homp_url', models.TextField(null=True)),
                ('cal_tel', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoanForHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_co_no', models.TextField()),
                ('kor_co_nm', models.TextField()),
                ('fin_prdt_cd', models.TextField(unique=True)),
                ('fin_prdt_nm', models.TextField()),
                ('loan_lmt', models.TextField(null=True)),
                ('loan_inci_expn', models.TextField(null=True)),
                ('erly_rpay_fee', models.TextField(null=True)),
                ('dly_rate', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoanForPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_co_no', models.TextField(unique=True)),
                ('kor_co_nm', models.TextField()),
                ('fin_prdt_cd', models.TextField()),
                ('fin_prdt_nm', models.TextField()),
                ('join_way', models.TextField(null=True)),
                ('crdt_prdt_type', models.TextField(null=True)),
                ('crdt_prdt_type_nm', models.TextField(null=True)),
                ('cb_name', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SavingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_co_no', models.TextField()),
                ('kor_co_nm', models.TextField()),
                ('fin_prdt_cd', models.TextField(unique=True)),
                ('fin_prdt_nm', models.TextField()),
                ('join_way', models.TextField(null=True)),
                ('join_member', models.TextField(null=True)),
                ('join_deny', models.IntegerField(null=True)),
                ('max_limit', models.TextField(null=True)),
                ('spcl_cnd', models.TextField(null=True)),
                ('mtrt_int', models.TextField(null=True)),
                ('etc_note', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SavingProductOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intr_rate_type', models.TextField(null=True)),
                ('intr_rate_type_nm', models.TextField(null=True)),
                ('intr_rate', models.FloatField(null=True)),
                ('intr_rate2', models.FloatField(null=True)),
                ('save_trm', models.IntegerField(null=True)),
                ('saving_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saving_product_option', to='financial_products.savingproduct', to_field='fin_prdt_cd')),
            ],
        ),
        migrations.CreateModel(
            name='LoanForPersonOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crdt_lend_rate_type', models.TextField(null=True)),
                ('crdt_lend_rate_type_nm', models.TextField(null=True)),
                ('crdt_grad_avg', models.TextField(null=True)),
                ('crdt_grad_1', models.TextField(null=True)),
                ('crdt_grad_4', models.TextField(null=True)),
                ('crdt_grad_5', models.TextField(null=True)),
                ('loan_person_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_person_product_option', to='financial_products.loanforperson', to_field='fin_co_no')),
            ],
        ),
        migrations.CreateModel(
            name='LoanForHomeOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lend_rate_type', models.TextField(null=True)),
                ('lend_rate_type_nm', models.TextField(null=True)),
                ('lend_rate_avg', models.TextField(null=True)),
                ('lend_rate_min', models.TextField(null=True)),
                ('lend_rate_max', models.TextField(null=True)),
                ('loan_home_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_home_product_option', to='financial_products.loanforhome', to_field='fin_prdt_cd')),
            ],
        ),
        migrations.CreateModel(
            name='DepositProductOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intr_rate_type', models.TextField(null=True)),
                ('intr_rate_type_nm', models.TextField(null=True)),
                ('intr_rate', models.FloatField(null=True)),
                ('intr_rate2', models.FloatField(null=True)),
                ('save_trm', models.IntegerField(null=True)),
                ('deposit_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_product_option', to='financial_products.depositproduct', to_field='fin_prdt_cd')),
            ],
        ),
    ]
