# Generated by Django 4.2.4 on 2023-11-20 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_stability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='stability',
        ),
        migrations.AddField(
            model_name='profile',
            name='stabillity',
            field=models.TextField(null=True),
        ),
    ]
